site_name: CMSDasStats
repo_name: GitHub
repo_url: https://github.com/CMSDAS/statistics-short-exercise
edit_uri: edit/master/docs

nav:
        - Home: index.md

theme:
        name: cinder
        include_sidebar: true
        highlightjs: true

extra_css:
  - "mystyle.css"

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
        - pymdownx.arithmatex
        - pymdownx.details
        - admonition
